name = "hoock-agency"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "hoockagency.com"
custom_domain = true

[[routes]]
pattern = "www.hoockagency.com"
custom_domain = true

[vars]
URI_STRAPI = "https://strong-art-a39006d263.strapiapp.com"
NEXT_PUBLIC_URI_STRAPI = "https://strong-art-a39006d263.strapiapp.com"
NEXT_PUBLIC_SITE_URL = "https://hoockagency.com"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6Lf3A4YsAAAAABJ4_7gKlQCBZdnd_E0LuCJh0PsY"
